### ISSUE TITLE
keyError: 'location'

### ISSUE THREAD

**Issue by gapthorpe** [tillsteinbach/VWsFriend#435]
I had it all working, but started receiving the following error message - not sure how to correct?  Thanks!

```
Traceback (most recent call last):
211
  File "/opt/venv/bin/vwsfriend", line 8, in <module>
212
    sys.exit(main())
213
             ^^^^^^
214
  File "/opt/venv/lib/python3.11/site-packages/vwsfriend/vwsfriend_base.py", line 327, in main
215
    weConnect = weconnect.WeConnect(username=weConnectUsername, password=weConnectPassword, spin=weConnectSpin, tokenfile=tokenfile,
216
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
217
  File "/opt/venv/lib/python3.11/site-packages/weconnect/weconnect.py", line 114, in __init__
218
    self.__session.login()
219
  File "/opt/venv/lib/python3.11/site-packages/weconnect/auth/we_connect_session.py", line 75, in login
220
    authorizationUrl = self.authorizationUrl(url='https://identity.vwgroup.io/oidc/v1/authorize')
221
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
222
  File "/opt/venv/lib/python3.11/site-packages/weconnect/auth/we_connect_session.py", line 96, in authorizationUrl
223
    redirect = tryLoginResponse.headers['Location']
224
               ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
225
  File "/opt/venv/lib/python3.11/site-packages/requests/structures.py", line 52, in __getitem__
226
    return self._store[key.lower()][1]
227
           ~~~~~~~~~~~^^^^^^^^^^^^^
228
KeyError: 'location'
```

**Comment by gapthorpe** [comment]
Spotted this in the Home Assistant integration also, so a wider problem?

`Logger: homeassistant.config_entries
Source: custom_components/volkswagen_we_connect_id/__init__.py:47 
Integration: Volkswagen We Connect ID 
First occurred: 15:05:41 (1 occurrences) 
Last logged: 15:05:41

Error setting up entry Volkswagen We Connect ID for volkswagen_we_connect_id
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/volkswagen_we_connect_id/__init__.py", line 47, in async_setup_entry
    await hass.async_add_executor_job(_we_connect.login)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/weconnect/weconnect.py", line 182, in login
    self.__session.login()
  File "/usr/local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 75, in login
    authorizationUrl = self.authorizationUrl(url='https://identity.vwgroup.io/oidc/v1/authorize')
  File "/usr/local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 96, in authorizationUrl
    redirect = tryLoginResponse.headers['Location']
  File "/usr/local/lib/python3.10/site-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'location'`

**Comment by bendavidson** [comment]
Tronity is also not updating so could be an issue VWs end (or they've
changed the API with no warning....)

**Comment by Kaputt4** [comment]
Same error here, lost connection with server at 15:30:00 CET (UTC +1), tried stopping everything and starting again with `docker-compose` but vwsfriend container returns the error stated above :worried:

Hope @tillsteinbach can find a fix

**Comment by Rocksteady0815** [comment]
Also, same error here.

**Comment by Toufinet** [comment]
Same here.

But Tronity is still working.

**Comment by bendavidson** [comment]
> Same here.
> 
> But Tronity is still working.

Tronity went down at the same time but came back about half 6 (UTC)

**Comment by tillsteinbach** [comment]
URLs in the API changed. Will fix it tomorrow.

**Comment by tillsteinbach** [comment]
Bug should be fixed and is in testing now. I probably can release a fixed version between noon and 1pm

**Comment by yngves** [comment]
Pulled from edge just now. Working as expected.

**Comment by Toufinet** [comment]
Thank you sir.

Can you fix weconnect-mqtt as well ?

**Comment by tillsteinbach** [comment]
Fixed in 0.23.7

**Comment by lubosramo** [comment]
New version did not resolved my problem. Or did I screwed something before?

I did install new version 0.23.7, restarted vwsfriend. Grafana loads, but every widget shows red exclamation mark, the same as yesterday.
In the right column I see:
"Warnings:
You have to set the URL for the VWsFriend user interface correctly: Go to the user interface on port 4000 and select "Database" > ”Connection Settings"
The engine type of null could not be detected yet. This should happen soon when receiving data.
Some panels need the timezone of null to be set. Please set the timezone here: Vehicle Parameters"

BUT - I can not load page on port 3000. I get browser error "ERR_CONNECTION_REFUSED". This was also yesterday (so before 0.23.7) but I thought that this problem will be resolved.

After running "docker-compose logs vwsfriend" I see at the ond of output this:
"vwsfriend_1   | vwsfriend: error: unrecognized arguments: Pin is only necessary for locking/unlocking in Homekit. If you don't want this keep WECONNECT_PIN empty
"

I have also Home Assistant integration of mitch-dc/volkswagen_we_connect_id, there is this error:

Logger: homeassistant.config_entries
Source: .local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py:96
First occurred: 8:32:08 PM (1 occurrences)
Last logged: 8:32:08 PM

Error setting up entry Volkswagen We Connect ID for volkswagen_we_connect_id
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/volkswagen_we_connect_id/__init__.py", line 47, in async_setup_entry
    await hass.async_add_executor_job(_we_connect.login)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/.local/lib/python3.10/site-packages/weconnect/weconnect.py", line 182, in login
    self.__session.login()
  File "/config/.local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 75, in login
    authorizationUrl = self.authorizationUrl(url='https://identity.vwgroup.io/oidc/v1/authorize')
  File "/config/.local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 96, in authorizationUrl
    redirect = tryLoginResponse.headers['Location']
  File "/usr/lib/python3.10/site-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'location'


Any help please?

**Comment by CrazySeb69** [comment]
Same problem from today's morning. Any way to fix it ?
